export const en = {
  openFile: 'Open file',
  close: 'Close',
  separator: 'Separator',
  comma: 'Comma ,',
  semicolon: 'Semicolon ;',
  tab: 'Tab',
  custom: 'Custom...',
  character: 'Character',
  rows: 'rows',
  noFile: 'No file loaded',
  hint: 'Open a .csv, .tsv, .txt, or .dat file to view its contents.',
  reading: 'Reading file...',
  errorSeparator: 'Enter a single character to use as the separator.',
  errorLength: 'Custom separators must be exactly one character.',
  errorSelect: 'Select file',
  themeLight: 'Light Theme',
  themeDark: 'Dark Theme',
  themeToggle: 'Toggle Theme',
  langToggle: 'Language',
  autoFitAll: 'Auto-fit all columns',
  dropOverlay: 'Drop file here to open',
  columns: 'columns',
  size: 'Size',
  delimiter: 'Delimiter',
  newTab: 'New Tab',
  row: 'Row',
  cellDetailEditor: 'Cell Detail Editor',
  confirmTitle: 'Confirm Separator',
  confirmMessage: 'You are opening the file "{name}". Confirm the separator to use, or select another:',
  confirmBtn: 'Open File',
  cancelBtn: 'Cancel',
  search: 'Search',
  replace: 'Replace',
  replaceAll: 'Replace All',
  matchCase: 'Match Case',
  matchWholeWord: 'Match Whole Word',
  useRegex: 'Use Regular Expression',
  searchInColumn: 'Search in column',
  allColumns: 'All columns',
  noResults: 'No results',
  matchCounter: '{current} of {total}',
  saveChanges: 'Save Changes',
  saveSuccess: 'File saved successfully!',
  saveError: 'Failed to save file: {error}',
  unsavedChanges: 'Unsaved changes',
  dragToMove: 'Drag to move',
  prevMatch: 'Previous Match (Shift+Enter)',
  nextMatch: 'Next Match (Enter)',
  expandCell: 'Expand Cell',
  discardUnsaved: 'Discard unsaved changes',
  discard: 'Discard',
  moreOptions: 'More Options',
  pressCtrlEnter: 'Press <strong>Ctrl</strong>+<strong>Enter</strong> to save, <strong>Esc</strong> to cancel',
  copy: 'Copy',
  copied: 'Copied!',
  errorUnknown: 'Unknown error',
  errorDiscardChanges: 'Failed to reload the file to discard changes.',
  errorFileDialog: 'The file dialog could not be opened.',
  errorFileNoLongerExists: 'File no longer exists at: {path}',
  errorFileRead: 'The selected file could not be read.',
  fileChangedTitle: 'File Changed',
  fileChangedMessage: 'The file "{name}" has been modified externally. Do you want to reload it? Any unsaved changes will be lost.',
  reloadBtn: 'Reload',
  ignoreBtn: 'Ignore',
  updateAvailableTitle: 'Update Available',
  updateAvailableMessage: 'A new version ({version}) of KipuView is available. Do you want to download and install it now?',
  updateError: 'Failed to check/apply updates: {error}',
  updateChecking: 'Checking for updates...',
  updateNoNewVersion: 'You are on the latest version.'
};

export type TranslationKeys = typeof en;
