import { TranslationKeys } from './en';

export const es: TranslationKeys = {
  openFile: 'Abrir archivo',
  close: 'Cerrar',
  separator: 'Separador',
  comma: 'Coma ,',
  semicolon: 'Punto y coma ;',
  tab: 'Tabulación',
  custom: 'Personalizado...',
  character: 'Carácter',
  rows: 'filas',
  noFile: 'Ningún archivo cargado',
  hint: 'Abra un archivo .csv, .tsv, .txt o .dat para ver su contenido.',
  reading: 'Leyendo archivo...',
  errorSeparator: 'Ingrese un solo carácter separador.',
  errorLength: 'El separador personalizado debe tener exactamente un carácter.',
  errorSelect: 'Seleccionar archivo',
  themeLight: 'Tema Claro',
  themeDark: 'Tema Oscuro',
  themeToggle: 'Cambiar Tema',
  langToggle: 'Idioma',
  autoFitAll: 'Ajustar todas las columnas',
  dropOverlay: 'Suelte el archivo aquí para abrir',
  columns: 'columnas',
  size: 'Tamaño',
  delimiter: 'Delimitador',
  newTab: 'Nueva pestaña',
  row: 'Fila',
  cellDetailEditor: 'Editor de detalle de celda',
  confirmTitle: 'Confirmar Separador',
  confirmMessage: 'Está abriendo el archivo "{name}". Confirme el separador a usar, o seleccione otro:',
  confirmBtn: 'Abrir archivo',
  cancelBtn: 'Cancelar',
  search: 'Buscar',
  replace: 'Reemplazar',
  replaceAll: 'Reemplazar todo',
  matchCase: 'Coincidir mayúsculas y minúsculas',
  matchWholeWord: 'Coincidir palabra completa',
  useRegex: 'Usar expresión regular',
  searchInColumn: 'Buscar en columna',
  allColumns: 'Todas las columnas',
  noResults: 'Sin resultados',
  matchCounter: '{current} de {total}',
  saveChanges: 'Guardar cambios',
  saveSuccess: '¡Archivo guardado con éxito!',
  saveError: 'Error al guardar el archivo: {error}',
  unsavedChanges: 'Cambios no guardados',
  dragToMove: 'Arrastrar para mover',
  prevMatch: 'Coincidencia anterior (Mayús+Enter)',
  nextMatch: 'Siguiente coincidencia (Enter)',
  expandCell: 'Expandir celda',
  discardUnsaved: 'Descartar cambios no guardados',
  discard: 'Descartar',
  moreOptions: 'Más opciones',
  pressCtrlEnter: 'Presione <strong>Ctrl</strong>+<strong>Enter</strong> para guardar, <strong>Esc</strong> para cancelar',
  copy: 'Copiar',
  copied: '¡Copiado!',
  errorUnknown: 'Error desconocido',
  errorDiscardChanges: 'Error al volver a cargar el archivo para descartar los cambios.',
  errorFileDialog: 'No se pudo abrir el diálogo de selección de archivo.',
  errorFileNoLongerExists: 'El archivo ya no existe en: {path}',
  errorFileRead: 'El archivo seleccionado no se pudo leer.',
  fileChangedTitle: 'Archivo modificado',
  fileChangedMessage: 'El archivo "{name}" ha sido modificado externamente. ¿Desea volver a cargarlo? Se perderá cualquier cambio no guardado.',
  reloadBtn: 'Recargar',
  ignoreBtn: 'Ignorar',
  updateAvailableTitle: 'Actualización disponible',
  updateAvailableMessage: 'Una nueva versión ({version}) de KipuView está disponible. ¿Desea descargarla e instalarla ahora?',
  updateError: 'Error al comprobar/aplicar actualizaciones: {error}',
  updateChecking: 'Buscando actualizaciones...',
  updateNoNewVersion: 'Ya tienes la última versión instalada.'
};
